// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210504185813_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Domain.WordGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .HasColumnType("TEXT");

                    b.Property<string>("WrongAnswer1")
                        .HasColumnType("TEXT");

                    b.Property<string>("WrongAnswer2")
                        .HasColumnType("TEXT");

                    b.Property<string>("WrongAnswer3")
                        .HasColumnType("TEXT");

                    b.Property<string>("WrongAnswer4")
                        .HasColumnType("TEXT");

                    b.Property<string>("WrongAnswer5")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WordGames");
                });
#pragma warning restore 612, 618
        }
    }
}
